// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID        int64
	PostID    int64
	ParentID  pgtype.Int8
	AuthorID  string
	Text      string
	CreatedAt pgtype.Timestamptz
}

type Post struct {
	ID              int64
	AuthorID        string
	Title           string
	Text            string
	CommentsAllowed bool
	CreatedAt       pgtype.Timestamptz
}
