// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addComment = `-- name: AddComment :one
INSERT INTO comments (post_id, parent_id, author_id, text) VALUES ($1, $2, $3, $4) RETURNING id, post_id, parent_id, author_id, text, created_at
`

type AddCommentParams struct {
	PostID   int64
	ParentID pgtype.Int8
	AuthorID string
	Text     string
}

func (q *Queries) AddComment(ctx context.Context, arg AddCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, addComment,
		arg.PostID,
		arg.ParentID,
		arg.AuthorID,
		arg.Text,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ParentID,
		&i.AuthorID,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (author_id, title, text) VALUES ($1, $2, $3) RETURNING id, author_id, title, text, comments_allowed, created_at
`

type CreatePostParams struct {
	AuthorID string
	Title    string
	Text     string
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost, arg.AuthorID, arg.Title, arg.Text)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Text,
		&i.CommentsAllowed,
		&i.CreatedAt,
	)
	return i, err
}

const currentSchema = `-- name: CurrentSchema :one
SELECT current_schema()::text
`

func (q *Queries) CurrentSchema(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, currentSchema)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const getComment = `-- name: GetComment :one
SELECT id, post_id, parent_id, author_id, text, created_at FROM comments WHERE id = $1
`

func (q *Queries) GetComment(ctx context.Context, id int64) (Comment, error) {
	row := q.db.QueryRow(ctx, getComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ParentID,
		&i.AuthorID,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}

const getComments = `-- name: GetComments :many
SELECT id, post_id, parent_id, author_id, text, created_at FROM comments WHERE id = ANY($1::bigint[])
`

func (q *Queries) GetComments(ctx context.Context, ids []int64) ([]Comment, error) {
	rows, err := q.db.Query(ctx, getComments, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.ParentID,
			&i.AuthorID,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPost = `-- name: GetPost :one
SELECT id, author_id, title, text, comments_allowed, created_at FROM posts WHERE id = $1
`

func (q *Queries) GetPost(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRow(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Text,
		&i.CommentsAllowed,
		&i.CreatedAt,
	)
	return i, err
}

const listCommentBranches = `-- name: ListCommentBranches :many
SELECT b.ordinality::integer AS branch_index, c.id, c.post_id, c.parent_id, c.author_id, c.text, c.created_at
FROM unnest($1::bigint[]) WITH ORDINALITY AS b(parent_id, ordinality)
CROSS JOIN LATERAL (
 SELECT id, post_id, parent_id, author_id, text, created_at FROM comments
 WHERE post_id = $2 AND parent_id = b.parent_id AND id > ($3::bigint[])[b.ordinality]
 ORDER BY id LIMIT ($4::integer[])[b.ordinality]
) c
ORDER BY b.ordinality, c.id
`

type ListCommentBranchesParams struct {
	ParentIds  []int64
	PostID     int64
	AfterIds   []int64
	PageLimits []int32
}

type ListCommentBranchesRow struct {
	BranchIndex int32
	ID          int64
	PostID      int64
	ParentID    pgtype.Int8
	AuthorID    string
	Text        string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListCommentBranches(ctx context.Context, arg ListCommentBranchesParams) ([]ListCommentBranchesRow, error) {
	rows, err := q.db.Query(ctx, listCommentBranches,
		arg.ParentIds,
		arg.PostID,
		arg.AfterIds,
		arg.PageLimits,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentBranchesRow{}
	for rows.Next() {
		var i ListCommentBranchesRow
		if err := rows.Scan(
			&i.BranchIndex,
			&i.ID,
			&i.PostID,
			&i.ParentID,
			&i.AuthorID,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentFeed = `-- name: ListCommentFeed :many
SELECT id, post_id, parent_id, author_id, text, created_at FROM comments WHERE post_id = $1 AND id > $2 ORDER BY id LIMIT $3
`

type ListCommentFeedParams struct {
	PostID int64
	ID     int64
	Limit  int32
}

func (q *Queries) ListCommentFeed(ctx context.Context, arg ListCommentFeedParams) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listCommentFeed, arg.PostID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.ParentID,
			&i.AuthorID,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPosts = `-- name: ListPosts :many
SELECT id, author_id, title, text, comments_allowed, created_at FROM posts WHERE id > $1 ORDER BY id LIMIT $2
`

type ListPostsParams struct {
	ID    int64
	Limit int32
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPosts, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Title,
			&i.Text,
			&i.CommentsAllowed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReplies = `-- name: ListReplies :many
SELECT id, post_id, parent_id, author_id, text, created_at FROM comments WHERE post_id = $1 AND parent_id = $2 AND id > $3 ORDER BY id LIMIT $4
`

type ListRepliesParams struct {
	PostID   int64
	ParentID pgtype.Int8
	ID       int64
	Limit    int32
}

func (q *Queries) ListReplies(ctx context.Context, arg ListRepliesParams) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listReplies,
		arg.PostID,
		arg.ParentID,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.ParentID,
			&i.AuthorID,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoots = `-- name: ListRoots :many
SELECT id, post_id, parent_id, author_id, text, created_at FROM comments WHERE post_id = $1 AND parent_id IS NULL AND id > $2 ORDER BY id LIMIT $3
`

type ListRootsParams struct {
	PostID int64
	ID     int64
	Limit  int32
}

func (q *Queries) ListRoots(ctx context.Context, arg ListRootsParams) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listRoots, arg.PostID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.ParentID,
			&i.AuthorID,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPost = `-- name: LockPost :one
SELECT id, author_id, title, text, comments_allowed, created_at FROM posts WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockPost(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRow(ctx, lockPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Text,
		&i.CommentsAllowed,
		&i.CreatedAt,
	)
	return i, err
}

const lockPostCreation = `-- name: LockPostCreation :exec
SELECT pg_advisory_xact_lock(19483726)
`

func (q *Queries) LockPostCreation(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockPostCreation)
	return err
}

const ready = `-- name: Ready :exec
SELECT id FROM posts LIMIT 0
`

func (q *Queries) Ready(ctx context.Context) error {
	_, err := q.db.Exec(ctx, ready)
	return err
}

const setCommentsAllowed = `-- name: SetCommentsAllowed :one
UPDATE posts SET comments_allowed = $2 WHERE id = $1 RETURNING id, author_id, title, text, comments_allowed, created_at
`

type SetCommentsAllowedParams struct {
	ID              int64
	CommentsAllowed bool
}

func (q *Queries) SetCommentsAllowed(ctx context.Context, arg SetCommentsAllowedParams) (Post, error) {
	row := q.db.QueryRow(ctx, setCommentsAllowed, arg.ID, arg.CommentsAllowed)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Text,
		&i.CommentsAllowed,
		&i.CreatedAt,
	)
	return i, err
}
