package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"example.com/ozon/internal/core"
	"example.com/ozon/internal/graph/model"
	"example.com/ozon/internal/stream"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, title string, text string) (*model.Post, error) {
	p, err := r.Service.CreatePost(ctx, actor(ctx), title, text)
	if err != nil {
		return nil, err
	}
	return postModel(p), nil
}

// SetCommentsAllowed is the resolver for the setCommentsAllowed field.
func (r *mutationResolver) SetCommentsAllowed(ctx context.Context, postID string, allowed bool) (*model.Post, error) {
	id, err := parseID(postID)
	if err != nil {
		return nil, err
	}
	p, err := r.Service.SetCommentsAllowed(ctx, actor(ctx), id, allowed)
	if err != nil {
		return nil, err
	}
	return postModel(p), nil
}

// AddComment is the resolver for the addComment field.
func (r *mutationResolver) AddComment(ctx context.Context, postID string, parentID *string, text string) (*model.Comment, error) {
	id, err := parseID(postID)
	if err != nil {
		return nil, err
	}
	parent, err := parseParent(parentID)
	if err != nil {
		return nil, err
	}
	c, err := r.Service.AddComment(ctx, actor(ctx), id, parent, text)
	if err != nil {
		return nil, err
	}
	return commentModel(c), nil
}

// CommentBranches is the resolver for the commentBranches field.
func (r *queryResolver) CommentBranches(ctx context.Context, postID string, branches []*model.BranchPageInput) ([]*model.CommentConnection, error) {
	id, err := parseID(postID)
	if err != nil {
		return nil, err
	}
	inputs := make([]core.BranchPageInput, len(branches))
	for i, b := range branches {
		parent, err := parseID(b.ParentID)
		if err != nil {
			return nil, err
		}
		inputs[i] = core.BranchPageInput{ParentID: parent, Page: pageInput(b.First, b.After)}
	}
	pages, err := r.Service.CommentBranches(ctx, id, inputs)
	if err != nil {
		return nil, err
	}
	result := make([]*model.CommentConnection, len(pages))
	for i, page := range pages {
		result[i] = commentConnection(page)
	}
	return result, nil
}

// CommentFeed is the resolver for the commentFeed field.
func (r *queryResolver) CommentFeed(ctx context.Context, postID string, first int, after *string) (*model.CommentConnection, error) {
	id, err := parseID(postID)
	if err != nil {
		return nil, err
	}
	page, err := r.Service.CommentFeed(ctx, id, pageInput(first, after))
	if err != nil {
		return nil, err
	}
	return commentConnection(page), nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, first int, after *string) (*model.PostConnection, error) {
	page, err := r.Service.Posts(ctx, pageInput(first, after))
	if err != nil {
		return nil, err
	}
	result := &model.PostConnection{Edges: make([]*model.PostEdge, 0, len(page.Edges)), PageInfo: &model.PageInfo{HasNextPage: page.PageInfo.HasNextPage, EndCursor: page.PageInfo.EndCursor}}
	for _, edge := range page.Edges {
		result.Edges = append(result.Edges, &model.PostEdge{Cursor: edge.Cursor, Node: postModel(edge.Node)})
	}
	return result, nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*model.Post, error) {
	value, err := parseID(id)
	if err != nil {
		return nil, err
	}
	p, err := r.Service.Post(ctx, value)
	if err != nil {
		return nil, err
	}
	return postModel(p), nil
}

// Comment is the resolver for the comment field.
func (r *queryResolver) Comment(ctx context.Context, id string) (*model.Comment, error) {
	value, err := parseID(id)
	if err != nil {
		return nil, err
	}
	c, err := r.Service.Comment(ctx, value)
	if err != nil {
		return nil, err
	}
	return commentModel(c), nil
}

// Comments is the resolver for the comments field.
func (r *queryResolver) Comments(ctx context.Context, postID string, parentID *string, first int, after *string) (*model.CommentConnection, error) {
	id, err := parseID(postID)
	if err != nil {
		return nil, err
	}
	parent, err := parseParent(parentID)
	if err != nil {
		return nil, err
	}
	page, err := r.Service.Comments(ctx, id, parent, pageInput(first, after))
	if err != nil {
		return nil, err
	}
	return commentConnection(page), nil
}

// CommentAdded is the resolver for the commentAdded field.
func (r *subscriptionResolver) CommentAdded(ctx context.Context, postID string) (<-chan *model.Comment, error) {
	id, err := parseID(postID)
	if err != nil {
		return nil, err
	}
	source, err := r.Service.Subscribe(ctx, id)
	if err != nil {
		return nil, err
	}
	stream.Ready(ctx)
	out := make(chan *model.Comment)
	go func() {
		defer close(out)
		for {
			select {
			case <-ctx.Done():
				return
			case c, ok := <-source:
				if !ok {
					return
				}
				select {
				case out <- commentModel(c):
				case <-ctx.Done():
					return
				}
			}
		}
	}()
	return out, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
